#!/bin/bash

# KDC Server 
#
# chkconfig: 2345 90 10
# description: krb5kdc 

source /etc/rc.d/init.d/functions

RETVAL=0
program="krb5kdc"
zkUser='root'
pro_bin=/usr/local/sbin/$program

start() {
  echo -n $"Starting $program"
  mypid=`pidof $program`
  if [ "$mypid" ];then
	echo "$desc is already running (pid $mypid)"
  else
	  daemon --user $zkUser $pro_bin 
	  RETVAL=$?
  fi
  echo
  [ $RETVAL -eq 0 ]
  return $RETVAL
}

stop() {
  echo -n $"Stopping $program: "
  mypid=`pidof $program`
  if [ "$mypid" ];then
        echo "killing $program (pid: $mypid)"
        kill -9 $mypid
	RETVAL=$?
  fi
    echo
  [ $RETVAL -eq 0 ]
}

restart() {
  stop
  start
}

checkstatus(){
  pidof $program 
  RETVAL=$?
  if [ $RETVAL -eq 0 ];then
	echo "$program is running"
  else
	echo "$program is not running."
  fi
}

condrestart(){
   restart
}

case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  status)
  checkstatus
  ;;
  restart)
  restart
  ;;
  condrestart)
  condrestart
  ;;
  *)
  echo $"Usage: $0 {start|stop|status|restart|condrestart}"
  exit 1
esac

exit $RETVAL
